### ISSUE TITLE
Feedback gives missing output / wrong count  ( half of the devices)

### ISSUE THREAD

**Issue by judgetr** [grocer/grocer#92]
Hello, i m currently testing with both of my iphone (iphone 6 - os 8.1.1, and iphone 5 - os 7.1.1 ) and even thou i deleted my application from both of them, when i tried to send notification on those devices it only retunrs iPhone 6's device token.

What should i investigate? Is it a problem from phone model? or maybe ios Version?

**Comment by stevenharman** [comment]
How are you sending the notifications? If you're sending them back to back, over the same connection I suspect you're falling victim to Issue #14 - Apple is closing the socket after the first bad notification and dropping the rest. Can you try sending them over different connections, or will a few seconds wait between them and then see what you get?

**Comment by judgetr** [comment]
hey @stevenharman , thanks for the quick response. I read that issue and thats why i tried to send the push notification to the only single deleted device token, so there is only push for one connection. I tried with another device iphone 4s 7.1.1 and it gives me failed attempt as it was suppose to do, but still no feedback on iphone 5 one.

for information this is how i test

pusher=Grocer.pusher(opt)
feedback=Grocer.feedback(opt)
notification=Grocer::Notification.new( device_token: token , badge: 2, alert: 'hello')
pusher.push(notification)

after that i iterate and it returns nil.

**Comment by stevenharman** [comment]
Well, darn. I wonder if you're also being bitten by #80 - the `#each` doesn't do what you'd expect it to do. Perhaps I should re-open that one and move forward with removing `Enumerable` support and instead adding our own API for iterating through feedback.

Could you try `#to_a` on the feedback to force it to all be read?

**Comment by judgetr** [comment]
@stevenharman , i looked over that issue aswell and i tried to see the count all i needed to see was '1' instead of 0 :) so i dont think thats it aswell, and after i tried to check it with to_a i get empty array anyway.

**Comment by stevenharman** [comment]
To clarify, after installing and enabling push notifications on three different phones, and then uninstalling the app on each, you're seeing the following results:

1. iPhone 6, iOS 8.1.1 - :white_check_mark: Feedback received
1. iPhone 5, iOS 7.1.1 - :no_entry: Feedback not received
1. iPhone 4S, iOS 7.1.1 - :white_check_mark: Feedback received

It sounds like perhaps that device 2 (iPhone 5) isn't properly being unregistered with APNS and so they're not reporting it via Feedback.

What happens if you open multiple push connections, push each notification, and then open a Feedback connection and read? We'd expect to get 3 Feedback notifications, but you're getting... how many?

**Comment by judgetr** [comment]
Yes exactly, for the first problem yes when i try to send in each loop it only gives one single feedback but when i send seperatly i only get 2  feedback.device_token where i should have get 3.

**Comment by stevenharman** [comment]
Hmmm... I have another idea. Perhaps the notification for the iPhone 5 isn't actually being accepted by APNS. That is, it could be "bad". In such a case, APNS will write an error message on the push notification connection before closing the socket. (See the docs around [Figure 5-2](https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html#//apple_ref/doc/uid/TP40008194-CH101-SW11) on how APNS handles bad notifications.) Because the notification was "bad" and never accepted by APNS, there won't be a feedback for it.

**Comment by stevenharman** [comment]
@judgetr Any luck? I'm wondering if there's something I can to help, or if this issue can be closed out. Please let me know. Thanks!

**Comment by judgetr** [comment]
@stevenharman i'v been struggling with other issues i couldnt give this topich the right amount of attention nor time, but i'll be investigate a bit more within this week, thank you for your concern.I think this issue should be stay open so we can communicate better.
Have a nice one

**Comment by pkuruppu** [comment]
+1
It looks like I'm having the same issue here. I'm using an iphone 6, and I'm able to successfully receive the notifications using grocer. However when I uninstall my ios application and try sending a notification, I don't see anything returned in my feedback. Feedback returns nil, and when I call .to_a on it before doing an .each, it returns an empty array.

**Comment by stevenharman** [comment]
@pkuruppu Do other devices work as expected?

**Comment by pkuruppu** [comment]
Yes - other devices do work as expected

**Comment by stevenharman** [comment]
Hello @pkuruppu. I'm going to close this Issue due to inactivity. Please re-open it if you are still experiencing the problem and/or have more information to add.

Thank you!
